# Generated by Django 3.0.8 on 2020-09-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.SmallIntegerField(max_length=5)),
                ('room_type', models.CharField(max_length=10)),
                ('capacity', models.SmallIntegerField(max_length=1)),
                ('rate', models.SmallIntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mail', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.SmallIntegerField(max_length=2)),
                ('chekindate', models.DateField(verbose_name='Checkin date')),
                ('chekoutdate', models.DateField(verbose_name='Checkout date')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotels.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotels.User')),
            ],
        ),
    ]
